Repository BHaddad1/cinemaquest, pull requests merged in 2023-02, with the labels that each got.

#1 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#9 Feature/arch
  public/facicon.ico
  public/favicon.ico
  public/index.html
  src/App.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Card/Card.test.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Form/Form.test.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/components/Movies/Movies.test.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/components/SingleMovie/SingleMovie.test.js
  src/data/movieData.js
  src/images/popcorn.png
  src/index.css
  src/index.js
Labels: documentation, enhancement, CSS, REACT JS

#12 Feature/refactor router
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.js
  src/index.js
Labels: enhancement, REACT JS

#13 Feature styling
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement, REACT JS

#14 Feature error
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Movies/Movies.js
Labels: REACT JS

#15 installed cypress and setup folders for testing
  cypress.config.js
  cypress/e2e/allmoviespage.cy.js
  cypress/e2e/singlemoviepage.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: enhancement, TEST

#17 Added new cypress test for single movie view
  cypress/e2e/singlemoviepage.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/singleMovie.json
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement, TEST

#18 Feature styling
  public/favicon.ico
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/SingleMovie/SingleMovie.css
Labels: enhancement, CSS, REACT JS

#19 Feature proptypes
  cypress/e2e/errorPage.cy.js
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Error/Error.js
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.js
Labels: enhancement, REACT JS, TEST

#20 Feature/searchbar
  src/components/App/App.css
  src/components/App/App.js
  src/components/Form/Form.css
  src/components/Form/Form.js
Labels: bug, enhancement, REACT JS

#21 Feature styling
  src/components/App/App.css
  src/components/App/App.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Movies/Movies.js
Labels: CSS

#24 Created a readme for our project
  README.md
Labels: documentation, enhancement

#30 fix: Add callback fcn to handleChange setState method, to show all mo…
  src/components/Form/Form.js
Labels: REACT JS
